### ISSUE TITLE
Failed to compile main.cpp

### ISSUE THREAD

**Issue by Triseedot** [canislupaster/cpu-vscode#1]
When I try to run a test on a windows system the extension executes the following command:
`C:\msys64\ucrt64\bin\g++.exe c:\vscode\main.cpp -o c:\Users\wdgsy\AppData\Roaming\Code\User\workspaceStorage\3a8f9f20aa8d565ce90154da10744f6d\thomasqm.cpu\build\3cf48a279327681f9f7f08cb5840f722 -Wall -std=c++20 -g -O2 `
Which results in a successful compiling and executable appearing in a desired location. However, I get a pop-up saying "Error compiling main.cpp:  Failed to compile main.cpp" and the process terminates.

**Comment by canislupaster** [comment]
hi, this should be fixed. please update to >= 0.2 and try again

**Comment by Triseedot** [comment]
Tests now run fine, thanks
