### ISSUE TITLE
Parse Contest as directories with template

### ISSUE THREAD

**Issue by xARSENICx** [canislupaster/cpu-vscode#3]
Add a feature to parse whole contest as directory with template solution files.

**Comment by canislupaster** [comment]
while there is currently no default shortcut, there are tasks for debug/run/run all, and you can easily bind shortcuts to them in VSCode preferences. do you think there should be a default shortcut for these?

**Comment by canislupaster** [comment]
lol what is this edit (you can set shortcuts in VSCode preferences). i'll see if there's a clean way to implement this feature later.

**Comment by xARSENICx** [comment]
yeah I realised the vs code preferences thing lol and didn't want to open another issue. sorry about that.
