### ISSUE TITLE
Unable to install extension for VS Code 1.91 version

### ISSUE THREAD

**Issue by rishiselvakumaran98** [canislupaster/cpu-vscode#4]
# Issue: Extension Compatibility with VS Code 1.91.0

I tried installing this extension for the latest VS Code version **1.91.0**, but unfortunately, it gives me the following message:

> "Can't install 'thomasqm.cpu' extension because it is not compatible with the current version of Visual Studio Code (version 1.91.0)."

## Extension Details:
- **Extension Name**: `thomasqm.cpu`
- **Extension Version**: v0.3.2

## Steps to Reproduce:
1. Update Visual Studio Code to version **1.91.0**.
2. Attempt to install the extension `thomasqm.cpu` (v0.3.2) via the marketplace.

## Expected Behavior:
The extension should install successfully and work with the latest version of VS Code.

## Actual Behavior:
The extension fails to install and displays the compatibility error message mentioned above.

## Suggested Solution:
Please update the extension to be compatible with VS Code version **1.91.0**.

Let me know if further information is needed. Thank you!

<img width="1174" alt="Screenshot 2024-11-17 at 11 50 35 AM" src="https://github.com/user-attachments/assets/bc20499f-cc73-445f-8163-4b0452a944d2">

**Comment by canislupaster** [comment]
this should be fixed. also, the latest vscode version is actually 1.95.3! consider upgrading

**Comment by rishiselvakumaran98** [comment]
Yep, it's fixed and thanks for reminding me to upgrade ;)
